version: "3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cartorio
    volumes:
      - mysql_data:/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOSTS: mysql

  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  mysql_data:
    driver: local
